# Generated by Django 3.2 on 2022-04-15 17:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, help_text='Warning editing this field will change the About Us section on the home page! Clear the field to display the default text.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Image of restaurant menu.', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(2, 'Two Person'), (4, 'Four Person')])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
        ),
    ]
