# Generated by Django 3.2 on 2022-04-15 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_auto_20220415_1700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(18, 0))),
                ('end_time', models.TimeField(editable=False)),
                ('party_size', models.IntegerField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people')], default=2)),
                ('table_numbers', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('updated', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_bookings', to=settings.AUTH_USER_MODEL)),
                ('tables', models.ManyToManyField(related_name='bookings', to='restaurant.Table')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
